#include "element_style.h"


QString ElementStyle::combo_styleSheet =
        "QComboBox{"
        "width:100px;"
        "height:27px;"
        "min-height:27px;"
        "min-width:100px;"
        "font-size:%1px;"
        "font-family:Microsoft YaHei;"
        "combobox-popup:0;"
        "border:1px;"
        "border-color:#CCCCCC;"
        "border-style:solid;"
        "radius:2px;"
        "outline:none;"
        "}"
        "QComboBox:hover{"
        "background-color:white;"
        "color:black;"
        "border:1px;"
        "border-color:rgb(77,156,248);"
        "border-style:solid;"
        "}"
        "QComboBox::down-arrow{"
        "width:12px;"
        "height:12px;"
        "image:url(:/image/combobox_arrow.png);"
        "}"
        "QComboBox::down-arrow:on{"
        "width:12px;"
        "height:12px;"
        "image:url(:/image/combobox_arrow_clicked.png);"
        "}"
        "QComboBox::drop-down{"
        "subcontrol-origin:padding;"
        "subcontrol-position:right;"
        "width:20px;"
        "border:0px;"
        "}"
        "QComboBox QAbstractItemView::item{"
        "min-height:26px;"
        "color:rgb(0,0,0);"
        "background-color:white;"
        "padding-left:3px;"
        "}"
        "QComboBox QAbstractItemView::item:hover{"
        "color:rgb(0,0,0);"
        "background-color:rgb(77,156,248);"
        "}"
        "QComboBox QAbstractScrollArea QScrollBar::vertical{"
        "width:10px;"
        "background-color:white;"
        "}"
        "QComboBox QAbstractScrollArea QScrollBar::handle::vertical{"
        "background:rgb(191,191,191);"
        "border-radius:2px;"
        "}"
        "QComboBox QAbstractScrollArea QScrollBar::handle:vertical:hover{"
        "background:rgb(128,128,128);"
        "border-radius:2px;"
        "}"
        "QComboBox QScrollBar::add-line::vertical{"
        "border:none;"
        "}"
        "QComboBox QScrollBar::sub-line::vertical{"
        "border:none;"
        "}";


ElementStyle::ElementStyle(QObject *parent) : QObject(parent)
{

}
