/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a impanel_adaptor.h: org.kde.impanel.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef IMPANEL_ADAPTOR_H
#define IMPANEL_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.kde.impanel
 */
class ImpanelAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.impanel")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.impanel\">\n"
"    <signal name=\"MovePreeditCaret\">\n"
"      <arg type=\"i\" name=\"position\"/>\n"
"    </signal>\n"
"    <signal name=\"SelectCandidate\">\n"
"      <arg type=\"i\" name=\"index\"/>\n"
"    </signal>\n"
"    <signal name=\"LookupTablePageUp\"/>\n"
"    <signal name=\"LookupTablePageDown\"/>\n"
"    <signal name=\"TriggerProperty\">\n"
"      <arg type=\"s\" name=\"key\"/>\n"
"    </signal>\n"
"    <signal name=\"PanelCreated\"/>\n"
"    <signal name=\"Exit\"/>\n"
"    <signal name=\"Restart\"/>\n"
"    <signal name=\"ReloadConfig\"/>\n"
"    <signal name=\"Configure\"/>\n"
"    <signal name=\"HiddenQimPanel\"/>\n"
"  </interface>\n"
        "")
public:
    ImpanelAdaptor(QObject *parent);
    virtual ~ImpanelAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void Configure();
    void Exit();
    void HiddenQimPanel();
    void LookupTablePageDown();
    void LookupTablePageUp();
    void MovePreeditCaret(int position);
    void PanelCreated();
    void ReloadConfig();
    void Restart();
    void SelectCandidate(int index);
    void TriggerProperty(const QString &key);
};

/*
 * Adaptor class for interface org.kde.impanel2
 */
class Impanel2Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.kde.impanel2")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.kde.impanel2\">\n"
"    <signal name=\"PanelCreated2\"/>\n"
"    <method name=\"SetSpotRect\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"x\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"y\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"w\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"h\"/>\n"
"    </method>\n"
"    <method name=\"SetLookupTable\">\n"
"      <arg direction=\"in\" type=\"as\" name=\"label\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"text\"/>\n"
"      <arg direction=\"in\" type=\"as\" name=\"attr\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"hasPrev\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"hasNext\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"cursor\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"layout\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    Impanel2Adaptor(QObject *parent);
    virtual ~Impanel2Adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void SetLookupTable(const QStringList &label, const QStringList &text, const QStringList &attr, bool hasPrev, bool hasNext, int cursor, int layout);
    void SetSpotRect(int x, int y, int w, int h);
Q_SIGNALS: // SIGNALS
    void PanelCreated2();
};

#endif
