/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i impanel_interface.h -p :impanel_interface.cpp org.kde.impanel.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "impanel_interface.h"
/*
 * Implementation of interface class OrgKdeImpanelInterface
 */

OrgKdeImpanelInterface::OrgKdeImpanelInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeImpanelInterface::~OrgKdeImpanelInterface()
{
}

/*
 * Implementation of interface class OrgKdeImpanel2Interface
 */

OrgKdeImpanel2Interface::OrgKdeImpanel2Interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgKdeImpanel2Interface::~OrgKdeImpanel2Interface()
{
}

